name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APK_SIGN_STORE_FILE: "android.keystore"

    steps:
      - name: extract keystore file
        env:
          APK_SIGN_STORE_FILE_CONTENT: ${{ secrets.APK_SIGN_STORE_FILE_CONTENT }}
        run: |
          echo $APK_SIGN_STORE_FILE_CONTENT | base64 --decode >> $APK_SIGN_STORE_FILE

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - uses: actions/checkout@v3

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build with Gradle
        run: ./gradlew build
        env:
          APK_SIGN_STORE_PASSWORD: ${{ secrets.APK_SIGN_STORE_PASSWORD }}
          APK_SIGN_KEY_ALIAS: ${{ secrets.APK_SIGN_KEY_ALIAS }}
          APK_SIGN_KEY_PASSWORD: ${{ secrets.APK_SIGN_KEY_PASSWORD }}